#!/bin/bash

set -e
set -u

if [ -d /results ] ; then
  # Running from Jenkins (RW)
  RESULTS="/results"
else
  # Running locally in Docker
  RESULTS="./results"
  mkdir -p "${RESULTS}"
fi

luacheck --formatter JUnit core plugins util > ${RESULTS}/prosody.luacheck
